from model.solution_mappings.dnme import DiagonalNoiseSolutionMapping
from model.solution_mappings.tnme import TriangularNoiseSolutionMapping
from model.solution_mappings.cmsm import ComposedMappedSolutionMapping
from model.solution_mappings.tvsm import TriangularVelocityFieldSolutionMapping
